import Head from "next/head";
import CommonBannner from "@/components/CommonBanner";
import Subscribe from "@/components/Subscribe";
import Filter from "@/components/Category/Filter";
import SingleProduct from "@/components/singleProduct";

export default function SingleProductCategory() {
  const product = {
    image: "./images/men-01.jpg",
    title: "Men Shirts Section",
    category: "Category",
    price: "$45.00",
    description:
      "Fam locavore kickstarter distillery. Mixtape chillwave tumeric sriracha taximy chia microdosing tilde DIY. XOXO fam indxgo   juiceramps cornhole raw denim forage brooklyn. Everyday carry +1 seitan poutine tumeric. Gastropub blue bottle austin listicle pour-over, neutra jean shorts keytar banjo tattooed umami cardigan.",
    reviewstotal: "4",
    sizes: ["SM", "M", "X", "XL"],
  };

  return (
    <>
      <Head>
        <title>Category</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SingleProduct product={product} />
      <Subscribe />
    </>
  );
}
