import Head from "next/head";
import CommonBannner from "@/components/CommonBanner";
import Subscribe from "@/components/Subscribe";
import Skills from "@/components/About/Skills";
import Team from "@/components/About/Team";

export default function About() {
  const team = [
    {
      image: "./images/team-member-01.jpg",
      name: "Akhil Katoch",
      desgination: "Product Caretaker",
      fb: "https://www.facebook.com/",
      insta: "https://www.instagram.com",
      twitter: "https://www.twitter.com",
      linkdin: "https://www.linkedin.com/",
    },
    {
      image: "./images/team-member-02.jpg",
      name: "Akhil Katoch",
      desgination: "Product Caretaker",
      fb: "https://www.facebook.com/",
      insta: "https://www.instagram.com",
      twitter: "https://www.twitter.com",
      linkdin: "https://www.linkedin.com/",
    },
    {
      image: "./images/team-member-03.jpg",
      name: "Akhil Katoch",
      desgination: "Product Caretaker",
      fb: "https://www.facebook.com/",
      insta: "https://www.instagram.com",
      twitter: "https://www.twitter.com",
      linkdin: "https://www.linkedin.com/",
    },
  ];

  return (
    <>
      <Head>
        <title>About Us</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <CommonBannner
        image="./images/about-us-page-heading.jpg"
        title="About us"
        subHeading="Our E-commerce App is awesome"
      />

      <Skills />
      <Team team={team} />
      <Subscribe />
    </>
  );
}
