import Head from "next/head";
import Subscribe from "@/components/Subscribe";
import CartTemplate from "@/components/Cart";

export default function Cart() {
  const products = [
    {
      image: "https://drive.google.com/uc?id=18KkAVkGFvaGNqPy2DIvTqmUH_nk39o3z",
      title: "Iphone 6S",
      category: "Category",
    },
    {
      image: "https://drive.google.com/uc?id=18KkAVkGFvaGNqPy2DIvTqmUH_nk39o3z",
      title: "Iphone 6S",
      category: "Category",
    },
    {
      image: "https://drive.google.com/uc?id=18KkAVkGFvaGNqPy2DIvTqmUH_nk39o3z",
      title: "Iphone 6S",
      category: "Category",
    },
  ];

  return (
    <>
      <Head>
        <title>Cart</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CartTemplate products={products} />
      <Subscribe />
    </>
  );
}
