import Head from "next/head";
import CommonBannner from "@/components/CommonBanner";
import Subscribe from "@/components/Subscribe";
import Category from "@/components/Products/Category";

export default function Products() {
  const categories = [
    {
      image: "./images/men-01.jpg",
      title: "Men Shirts Section",
      price: "$45.00",
    },
    {
      image: "./images/men-02.jpg",
      title: "Men Jeans Section",
      price: "$120.00",
    },
    {
      image: "./images/men-03.jpg",
      title: "Men Shoes Section",
      price: "$120.00",
    },
    {
      image: "./images/women-01.jpg",
      title: "Women Shirts Section",
      price: "$120.00",
    },
    {
      image: "./images/women-02.jpg",
      title: "Women jeans Section",
      price: "$120.00",
    },
    {
      image: "./images/women-03.jpg",
      title: "Women Shoes Section",
      price: "$120.00",
    },
  ];
  return (
    <>
      <Head>
        <title>Products | E-commerce</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CommonBannner
        image="./images/products-page-heading.jpg"
        title="Products"
        subHeading="Our E-commerce App is awesome"
      />
      <Category categories={categories} />
      <Subscribe />
    </>
  );
}
